version: 0.1.5.{build}
image:
- Visual Studio 2017
environment:
  version: 0.1.5
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "$(version).0"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
configuration: Release
before_build:
- cmd: >-
    nuget restore

    xcopy /Y /E packages\winpty.NET.0.4.2\content src\tterm
after_build:
- cmd: >-
    cd bin\Release

    7z a -tzip -mx9 -mtc=off -r ..\..\artefacts\tterm-v%version%.zip *.dll *.exe *.config winpty > nul
artifacts:
- path: 'artefacts\tterm-v$(version).zip'
deploy:
  provider: GitHub
  auth_token:
    secure: 49K/y43epwh5Sb8uY1l/TbIFRPcEq6fraQaYGS0bgWQJfONznd6hCqPUCg7WSX16
  artifact: artefacts\tterm-v$(version).zip
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
